<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="/admin">
        <img src="https://cdn-icons-png.flaticon.com/512/3093/3093000.png" width="30" height="30" alt="">
        Administrativo
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item active">
                <a class="nav-link" href="/admin">Inicio</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/cadastrar_cursos">Cadastrar Cursos</a>
            </li>
        </ul>
    </div>
</nav>