<div class="container h-100 d-flex justify-content-center align-items-center">
  <div class="card" style="width: 40rem; ">
    <div class="card-body">

      <div class="d-flex justify-content-center">
      </div>

      <div class="row">
        <div class="col">
          <h2 class="title">Cadastrar curso</h2>
        </div>
      </div>

      <div class="row">
        <div class="col">

          <form action="/registrar_cursos" method="post">
            <div class="form-group">
              <input type="text" name="name" class="form-control" placeholder="Nome">
            </div>
            <div class="form-group">
              <input type="text" name="description" class="form-control" placeholder="Descrição">
            </div>

            <div class="form-group">
              <input type="text" name="category" class="form-control" placeholder="Categoria">
            </div>
            <div class="form-group">
              <input type="text" value="0" name="qty_lesson" class="form-control" placeholder="Quantidade de aulas" hidden disabled>
            </div>
            <div class="form-group">
              <input type="text" value="0" name="total_hours" class="form-control" placeholder="Total de horas" hidden disabled>
            </div>

            <button type="submit" class="btn btn-success btn-block">Cadastrar</button>
            <a href="/admin" class="btn btn-secondary btn-block ">voltar</a>

          </form>

        </div>
      </div>

    </div>
  </div>
</div>