<div class="container-fluid h-100">
	<div class="row h-100">

		<div class="col-md-6 banner">
			<div class="row h-100 justify-content-center align-items-center">
				<div>
					<div class="communicationItem">

						Aprimore suas habilidades e alcance seu potencial com nossos cursos.
					</div>
					<div class="communicationItem">

						Cursos acessíveis para todos - investir em educação nunca foi tão fácil.
					</div>
					<div class="communicationItem">

						Mude sua trajetória profissional.
					</div>
				</div>
			</div>
		</div>

		<div class="col-md-6 pt-4 pl-5 pr-5 d-flex align-items-center">
			<div class="login-card">
				<form method="post" action="/autenticar">
					<div class="d-flex flex-column justify-content-center">
						<div class="p-3">
							<input type="text" name="email" class="form-control" placeholder="E-mail">
						</div>
						<div class="p-3">
							<input type="password" name="password" class="form-control" placeholder="Senha">
						</div>
						<div class="p-3">
							<button type="submit" class="btn btn-primary btn-block mb-2">Entrar</button>
						</div>
						<?php if ($this->view->login == 'erro') { ?>
							<span class="px-3 text text-danger">*E-mail e ou senha inválidos.</span>
						<?php } ?>
					</div>
				</form>

				<hr>

				<div class="row">
					<div class="col pl-5 pr-5 d-flex flex-column ">
						<h1 class="title">Junte-se à nossa comunidade de alunos dedicados</h1>

						<h2 class="mt- subtitle">Inicie sua jornada de aprendizado conosco.</h2>
						<a href="/inscreverse" class="btn btn-success btn-block mb-2">Criar Conta</a>
					</div>
				</div>
			</div>


		</div>

	</div>
</div>