<div class="container h-100 d-flex justify-content-center align-items-center">
  <div class="card" style="width: 40rem; ">
    <div class="card-body">

      <div class="d-flex justify-content-center">
      </div>

      <div class="row">
        <div class="col">
          <h2 class="title">Crie sua conta</h2>
        </div>
      </div>

      <div class="row">
        <div class="col">

          <form action="/registrar" method="post">
            <div class="form-group">
              <input type="text" value="<?= $this->view->user['name'] ?>" name="name" class="form-control" placeholder="Nome">
            </div>

            <div class="form-group">
              <input type="text" value="<?= $this->view->user['email'] ?>" name="email" class="form-control" placeholder="E-mail">
            </div>

            <div class="form-group">
              <input type="password" value="<?= $this->view->user['password'] ?>" name="password" class="form-control" placeholder="Senha">
            </div>

            <div class="mt-4 mb-4">
              <small class="form-text">
                Ao inscrever-se, você concorda com os <a href="">Termos de Serviço</a> e com as <a href="">Políticas de Privacidade</a>, incluindo o Uso de Cookies. Outras pessoas poderão encontrar você pelo e-mail ou número de telefone fornecido · Opções de Privacidade
              </small>
            </div>
            <button type="submit" class="btn btn-success btn-block">Inscrever-se</button>
            <a href="/" class="btn btn-secondary btn-block ">voltar</a>

            <?php if ($this->view->errorSignin) {   ?>

              <small class="form-text text-danger">"Erro ao tentar criar conta, verifique se os campos foram preenchidos corretamente."</small>

            <?php } ?>

          </form>

        </div>
      </div>

    </div>
  </div>
</div>