<div class="container h-100 d-flex justify-content-center align-items-center">
    <div class="card" style="width: 36rem;">
        <div class="card-body">
            <div class="row">
                <div class="col">
                    <h2 class="title d-flex justify-content-center">Conta criada com sucesso</h2>
                </div>
            </div>

            <div class="row">
                <div class="col">
                    <a href="/" class="btn btn-primary btn-block">Clique aqui para fazer login!</a>
                </div>
            </div>

        </div>
    </div>
</div>