<div class="container">

<div class="row profile">
    <?php include ('profileSidebar.phtml'); ?>
     <div class="col-md-9 order-content">

         <div class="form_main col-md-4 col-sm-5 col-xs-7">
             <form>
                 <div class="form-group">
                     <label for="name">Nome</label>
                     <input type="text" class="form-control shadow-outline-none" id="name" aria-describedby="name" placeholder="Nome">
                 </div>
                 <div class="form-group">
                     <label for="email">Email</label>
                     <input type="email" class="form-control" id="email" aria-describedby="email" placeholder="Email" disabled>
                 </div>
                 <div class="form-group">
                     <label for="password">Senha</label>
                     <input type="password" class="form-control shadow-outline-none" id="password" placeholder="Senha">
                 </div>
                 <button type="submit" class="btn btn-primary mt-3">Atualizar</button>
             </form>
         </div>

     </div>
 </div>
</div>