<div class="col-md-3">
              <div class="profile-sidebar">
                  <!-- Sidebar User -->
                  <div class="profile-userpic d-flex justify-content-center">
                      <img src="https://gravatar.com/avatar/31b64e4876d603ce78e04102c67d6144?s=80&d=https://codepen.io/assets/avatars/user-avatar-80x80-bdcd44a3bfb9a5fd01eb8b86f9e033fa1a9897c3a15b33adfc2649a002dab1b6.png" width="80" height="80" class="img-responsive" alt="UserAvatar">
                  </div>
    
                  <div class="profile-usertitle">
                      <div class="profile-usertitle-name">
                          <?= $_SESSION['name'] ?>
                      </div>
                  </div>
                  <div class="profile-usertitle">
                      <div class="profile-usertitle-email"> <!-- trocar classe-->
                      <?= $_SESSION['email'] ?>
                      </div>
                  </div>
                  <!-- End Sidebar User -->
                  <!-- Sidebar Menu -->
                  <div class="profile-usermenu ">
                      <ul class="nav d-flex flex-column">
                          <li>
                              <a href="/dashboard">
                                  <i class="glyphicon glyphicon-home"></i>
                                  Início </a>
                          </li>
                          <li>
                              <a href="/meus_cursos">
                                  <i class="glyphicon glyphicon-home"></i>
                                  Cursos </a>
                          </li>
                          <li>
                              <a href="/meu_perfil">
                                  <i class="glyphicon glyphicon-user"></i>
                                  Perfil </a>
                          </li>
                          <li>
                              <a href="/certificados">
                                  <i class="glyphicon glyphicon-ok"></i>
                                  Certificados </a>
                          </li>
                          <li>
                              <a href="/ajuda">
                                  <i class="glyphicon glyphicon-flag"></i>
                                  Ajuda </a>
                          </li>
                          <li>
                              <a href="/logout">
                                  <i class="glyphicon glyphicon-flag"></i>
                                  Sair </a>
                          </li>
                      </ul>
                  </div>
                  <!-- End Menu -->
    
                  <div class="portlet light bordered">
                      <!-- Status -->
                      <div class="row list-separated profile-stat">
                          <div class="col-md-4 col-sm-4 col-xs-6">
                              <div class="uppercase profile-stat-title"><a href="#" class="text-decoration-none text-reset">3</a></div>
                              <div class="uppercase profile-stat-text"><a href="#" class="text-decoration-none text-reset">Todos os cursos</a></div>
                          </div>
                          <div class="col-md-4 col-sm-4 col-xs-6">
                              <div class="uppercase profile-stat-title"><a href="#" class="text-decoration-none text-reset">4</a></div>
                              <div class="uppercase profile-stat-text"><a href="" class="text-decoration-none text-reset">Lista de desejos</a></div>
                          </div>
                          <div class="col-md-4 col-sm-4 col-xs-6">
                              <div class="uppercase profile-stat-title"><a href="#" class="text-decoration-none text-reset">6</a></div>
                              <div class="uppercase profile-stat-text"><a href="" class="text-decoration-none text-reset">Cursos Arquivados</a></div>
                          </div>
                      </div>
                      <!-- End Status -->
                      <!-- About User -->
                      <div>
                          <h4 class="profile-desc-title">About Nome</h4>
                          <span class="profile-desc-text"> Lorem ipsum dolor sit amet diam nonummy nibh dolore.
                          </span>
                          <div class="margin-top-20 profile-desc-link">
                              <i class="fa fa-globe"></i>
                              <a href="https://github.com/oaleekis">My website</a>
                          </div>
                          <div class="margin-top-20 profile-desc-link">
                              <i class="fa fa-github"></i>
                              <a href="https://github.com/oaleekis">My git</a>
                          </div>
                      </div>
                      <!-- End About -->
                  </div>
    
    
    
              </div>
          </div>